# Generated by Django 6.0.5 on 2026-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cedula',
            field=models.CharField(default='', max_length=20, verbose_name='Cédula de Ciudadanía'),
        ),
    ]
